### ISSUE TITLE
Failed to load DLL

### ISSUE THREAD

**Issue by blackarcher21** [myQwil/foo_pd#1]
I install all the content of components folder (foo_pd.dll, libpd.dll and pd folder ).

I got this message:
Failed to load DLL: foo_pd.dll
Reason: This component is missing a required dependency, or was made for different version of foobar2000.

I use latest beta v1.4.1 beta 2 and also test with v1.3.20 
I hope you will fix this and update SDK so it will appear on decoding page on v1.4 or newer. Thanks.

**Comment by myQwil** [comment]
Hi blackarcher21, I'm sorry to hear that it's not working for you. I'm currently using foobar2000 v1.4 on Windows 10. Everything seems to be working on my end. Does this message appear when you open foobar2000? I'll see what I can do about updating the SDK and hopefully that'll solve whatever issue you're having.

**Comment by blackarcher21** [comment]
Yes, the message appears on foobar2000 startup. At least I try with fresh portable which doesn't seem to work as well. I'm using Windows 10. I just wonder if I missing some dependencies on my OS. Thanks for the reply anyway :)

**Comment by myQwil** [comment]
is libpd.dll in the same folder as foo_pd.dll? I will get this error message when foo_pd.dll can't find libpd.dll.

**Comment by blackarcher21** [comment]
Yes, it is.

**Comment by blackarcher21** [comment]
Okay, I just found the tool for looking dependencies, so the missing dependencies are libgcc_s_dw2-1.dll and libwinpthread-1.dll. I test put them on same folder and now it works.

**Comment by blackarcher21** [comment]
I forgot to tell, they are coming from libpd.ll, which probably issue with the compilation not static  :)

**Comment by myQwil** [comment]
Interesting. I've made some changes to the project that sound like they might address the static issue. I'll also be sure to test out the portable version soon.

**Comment by myQwil** [comment]
I've committed an update and it seems to work without requiring the extra dependencies on the portable version of fb2k, so hopefully that works out on your end as well.

**Comment by blackarcher21** [comment]
The problem still exists. Do you have mingw32 on your path? If I set it to my PATH, the component works. I have MSYS2 installed but still don't how to compile the libpd.dll.

**Comment by myQwil** [comment]
I don't have mingw32 in my path, but maybe some other path entry is helping things run more smoothly.

For compiling libpd, you would run these commands in msys2 mingw 32bit:
`pacman -S git`
`git clone https://github.com/libpd/libpd.git`
`cd libpd`
`git submodule init`
`git submodule update`
`pacman -S mingw-w64-i686-toolchain mingw-w64-i686-clang make`
`make`

Then from there, you add externals in the pure-data folder. You can see how I do it in a folder called building-libpd, which I've just added.

**Comment by blackarcher21** [comment]
Thanks. I will try to compile libpd.dll myself and try to find how remove those two dll dependencies. It will take some time to download the requirement for compiling (I don't have clang installed yet), internet speed here is bad 😄 
Regards.

**Comment by blackarcher21** [comment]
It looks like the compile run with mingw but stop in the middle, miss bassemu~ from the sources. Where I can find it? Thanks.

**Comment by myQwil** [comment]
My bad, there was a line in my .gitignore that was preventing folders with a tilde in the name from uploading. bassemu~ and a few others should be there now.

**Comment by myQwil** [comment]
for all of the external source files, you can go here to download a snapshot:
https://sourceforge.net/p/pure-data/svn/HEAD/tree/trunk/externals/
You have to wait a while for the server to respond

**Comment by blackarcher21** [comment]
Yes, I searched bassemu~ and got from sourceforge.  I somehow managed to solved the problem by adding -Bstatic on MINGW_LDFLAGS line 27 of Makefile, now no more libwinpthread-1.dll as dependency. Regards. 😄
